const C=document.getElementById('world'),ctx=C.getContext('2d');let W=innerWidth,H=innerHeight,DPR=1;const A={};for(const[k,v]of Object.entries(window.RSK_ASSETS||{})){A[k]=new Image();A[k].src=v}function resize(){DPR=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;C.width=W*DPR;C.height=H*DPR;ctx.setTransform(DPR,0,0,DPR,0,0)}addEventListener('resize',resize);resize();
const defaults={gold:120,wood:80,food:60,pop:4,cap:12,day:1,level:1,hp:100,score:0};let ui={...defaults},running=false,time=0,worldX=0,horse=false,spawn=0,night=false,msg='ابنِ اقتصادك واستعد لليل.',units=[],buildings=[{type:'castle',x:520}],particles=[],trees=[],gameOver=false,selectedBuild=null;
const rnd=(a,b)=>a+Math.random()*(b-a),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),ground=()=>H*.72;function say(s){msg=s;const e=document.getElementById('message');if(e)e.textContent=s}function sync(){for(const k of['gold','wood','food','day','level']){const e=document.getElementById(k);if(e)e.textContent=Math.floor(ui[k])}const p=document.getElementById('pop');if(p)p.textContent=ui.pop+'/'+ui.cap;const ph=document.getElementById('phase');if(ph)ph.textContent=night?'ليل':'نهار';const hp=document.getElementById('castleHp');if(hp)hp.textContent=Math.max(0,Math.floor(ui.hp))}
for(let i=0;i<70;i++)trees.push({x:i*125+rnd(-45,45),s:rnd(.7,1.25)});
function sky(){const g=ctx.createLinearGradient(0,0,0,H);if(night){g.addColorStop(0,'#080d1d');g.addColorStop(.55,'#1b2b45');g.addColorStop(1,'#574737')}else{g.addColorStop(0,'#65b8e4');g.addColorStop(.55,'#c9e4d0');g.addColorStop(1,'#d5b978')}ctx.fillStyle=g;ctx.fillRect(0,0,W,H)}
function tree(x,y,s){ctx.save();ctx.translate(x,y);ctx.scale(s,s);ctx.fillStyle='#493322';ctx.fillRect(-7,-46,14,49);for(const q of[[0,-70,37],[-24,-51,25],[24,-51,25]]){ctx.fillStyle='#244f37';ctx.beginPath();ctx.arc(q[0],q[1],q[2],0,7);ctx.fill()}ctx.fillStyle='#46784b';ctx.beginPath();ctx.arc(-10,-75,18,0,7);ctx.fill();ctx.restore()}
function sprite(kind,x,y,scale=1){const im=A[kind+'.png'];if(!im||!im.complete||!im.naturalWidth)return;const count=kind==='king'?8:6,fw=im.naturalWidth/count,fh=im.naturalHeight,frame=Math.floor(time*7)%count;ctx.imageSmoothingEnabled=false;ctx.drawImage(im,frame*fw,0,fw,fh,x-fw*scale/2,y-fh*scale+Math.sin(time*7+x*.01)*1.4,fw*scale,fh*scale)}
function building(b){const x=b.x-worldX,y=ground();if(x<-180||x>W+180)return;const im=A[b.type+'.png'];if(im&&im.complete){const sz=b.type==='castle'?[175,145]:b.type==='wall'?[135,100]:[130,110];ctx.drawImage(im,x-sz[0]/2,y-sz[1],sz[0],sz[1]);}else{ctx.fillStyle='#777';ctx.fillRect(x-50,y-80,100,80)}}
function burst(x,y,hit=false){for(let i=0;i<(hit?18:10);i++)particles.push({x,y,vx:rnd(-90,90),vy:rnd(-150,-30),life:.7,max:.7,hit})}
function build(type){const cost={farm:[30,0],house:[35,0],wall:[0,25],tower:[70,0],worker:[20,0],archer:[45,0]}[type];if(!cost||ui.gold<cost[0]||ui.wood<cost[1])return say('الموارد غير كافية');if((type==='worker'||type==='archer')&&ui.pop>=ui.cap)return say('لا توجد مساكن كافية');ui.gold-=cost[0];ui.wood-=cost[1];const x=worldX+W*.5+rnd(-230,230);if(type==='worker'||type==='archer'){ui.pop++;units.push({kind:type,x:x+100,hp:type==='archer'?4:2});say(type==='archer'?'تم تجنيد رامي.':'تم توظيف عامل.')}else{buildings.push({type,x});if(type==='house')ui.cap+=4;say('تم بناء '+({farm:'مزرعة',house:'مسكن',wall:'سور',tower:'برج'}[type]))}sync()}
function save(){localStorage.setItem('rsk_save',JSON.stringify({ui,time,worldX,horse,night,units,buildings}));say('تم حفظ المملكة.')}function load(){try{const s=JSON.parse(localStorage.getItem('rsk_save'));if(!s)return say('لا يوجد حفظ سابق.');Object.assign(window,{dummy:0});ui=s.ui;time=s.time;worldX=s.worldX;horse=s.horse;night=s.night;units=s.units||[];buildings=s.buildings||[{type:'castle',x:520}];say('تم تحميل المملكة.');sync()}catch(e){say('تعذر تحميل الحفظ.')}}
document.querySelectorAll('#buildbar button[data-build]').forEach(b=>b.onclick=()=>build(b.dataset.build));document.getElementById('left').onpointerdown=()=>worldX-=55;document.getElementById('right').onpointerdown=()=>worldX+=55;document.getElementById('horse').onclick=()=>{horse=!horse;say(horse?'امتطيت الجواد.':'ترجلت من الجواد.')};document.getElementById('save').onclick=save;document.getElementById('load').onclick=load;document.getElementById('startBtn').onclick=()=>{running=true;document.getElementById('start').style.display='none';say('بدأت المملكة. ابنِ اقتصادك واستعد لهجمات الليل.');sync()};
function update(dt){if(!running||gameOver)return;time+=dt;const day=Math.floor(time/48)+1;if(day!==ui.day){ui.day=day;ui.gold+=18+units.filter(u=>u.kind==='worker').length*5;ui.wood+=10+buildings.filter(b=>b.type==='farm').length*2;ui.food+=15+units.filter(u=>u.kind==='worker').length*2;ui.level=Math.min(10,1+Math.floor(ui.day/3));ui.score+=50;say('بدأ يوم جديد. ازدهرت المملكة.')}night=time%48>32;spawn+=dt;if(night&&spawn>Math.max(2.5,5-ui.level*.2)){spawn=0;const n=Math.min(2+Math.floor(ui.day/2),10);for(let i=0;i<n;i++)units.push({kind:'enemy',x:worldX+W+rnd(140,700),hp:3+Math.floor(ui.day/5),atk:0})}
for(const u of units){if(u.kind==='worker'){u.x+=Math.sin(time+u.x)*dt*6}else if(u.kind==='enemy'){const target=worldX+W*.5;u.x-=dt*(18+ui.day*1.4);u.atk=(u.atk||0)+dt;if(Math.abs(u.x-target)<95&&u.atk>.8){u.atk=0;ui.hp-=4;burst(u.x-worldX,ground()-45,true);if(ui.hp<=0){ui.hp=0;gameOver=true;say('سقطت المملكة. أعد المحاولة.')}}}}
const archers=units.filter(u=>u.kind==='archer'),enemies=units.filter(u=>u.kind==='enemy');for(const a of archers)for(const e of enemies)if(Math.abs(a.x-e.x)<210&&Math.random()<dt*1.9){e.hp--;burst(e.x-worldX,ground()-65,true);if(e.hp<=0)ui.score+=10}units=units.filter(u=>u.kind!=='enemy'||u.hp>0);ui.gold+=units.filter(u=>u.kind==='worker').length*dt*.1;ui.wood+=buildings.filter(b=>b.type==='farm').length*dt*.04;ui.food=Math.max(0,ui.food-units.length*dt*.012);for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=220*dt;p.life-=dt}particles=particles.filter(p=>p.life>0);sync()}
function render(){sky();const gy=ground();ctx.fillStyle='#4c7944';ctx.fillRect(0,gy,W,H-gy);for(let x=-(worldX%64);x<W;x+=64){ctx.fillStyle='#65934f';ctx.fillRect(x,gy,40,3)}for(const t of trees){const x=t.x-worldX;if(x>-100&&x<W+100)tree(x,gy,t.s)}for(const b of buildings)building(b);for(const u of units)if(u.kind!=='enemy')sprite(u.kind,u.x-worldX,gy+2,u.kind==='archer'?.82:.82);for(const e of units)if(e.kind==='enemy')sprite('enemy',e.x-worldX,gy+2,1);sprite('king',W*.5,gy-2,horse?1.22:1.15);for(const p of particles){ctx.globalAlpha=clamp(p.life/p.max,0,1);ctx.fillStyle=p.hit?'#ff735f':'#f3ca63';ctx.fillRect(p.x,p.y,4,4);ctx.globalAlpha=1}if(night){ctx.fillStyle='rgba(5,9,22,.4)';ctx.fillRect(0,0,W,H);ctx.fillStyle='#f4e4ad';ctx.beginPath();ctx.arc(W-90,95,30,0,7);ctx.fill()}if(gameOver){ctx.fillStyle='rgba(4,7,12,.78)';ctx.fillRect(0,0,W,H);ctx.fillStyle='#fff';ctx.textAlign='center';ctx.font='700 34px system-ui';ctx.fillText('سقطت المملكة',W/2,H/2-25);ctx.font='18px system-ui';ctx.fillText('أعد تحميل الصفحة لبدء حملة جديدة',W/2,H/2+20);ctx.textAlign='start'}}
let last=performance.now();function loop(now){const dt=Math.min(.05,(now-last)/1000);last=now;update(dt);render();requestAnimationFrame(loop)}sync();loop(last);