const C=document.getElementById('world'),ctx=C.getContext('2d');let W=innerWidth,H=innerHeight,DPR=1;const A={};for(const[k,v]of Object.entries(window.RSK_ASSETS||{})){A[k]=new Image();A[k].src=v}function resize(){DPR=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;C.width=W*DPR;C.height=H*DPR;ctx.setTransform(DPR,0,0,DPR,0,0)}addEventListener('resize',resize);resize();
const defaults={gold:120,wood:80,food:60,pop:4,cap:12,day:1,level:1,hp:100};let ui={...defaults},running=false,time=0,worldX=0,horse=false,spawn=0,night=false,msg='ابنِ اقتصادك واستعد لليل.',units=[],buildings=[{type:'castle',x:520}],particles=[],trees=[],gameOver=false;
const rnd=(a,b)=>a+Math.random()*(b-a),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),ground=()=>H*.72;function say(s){msg=s;const e=document.getElementById('message');if(e)e.textContent=s}function sync(){for(const k of['gold','wood','food','day','level'])document.getElementById(k).textContent=Math.floor(ui[k]);document.getElementById('pop').textContent=ui.pop+'/'+ui.cap;document.getElementById('phase').textContent=night?'ليل':'نهار';document.getElementById('castleHp').textContent=Math.max(0,Math.floor(ui.hp))}
for(let i=0;i<55;i++)trees.push({x:i*145+rnd(-45,45),s:rnd(.75,1.2)});
function sky(){const g=ctx.createLinearGradient(0,0,0,H);if(night){g.addColorStop(0,'#0b1224');g.addColorStop(.55,'#24344d');g.addColorStop(1,'#5a4938')}else{g.addColorStop(0,'#67bde8');g.addColorStop(.55,'#c6e5d2');g.addColorStop(1,'#d9bf83')}ctx.fillStyle=g;ctx.fillRect(0,0,W,H)}function tree(x,y,s){ctx.save();ctx.translate(x,y);ctx.scale(s,s);ctx.fillStyle='#513725';ctx.fillRect(-7,-45,14,48);ctx.fillStyle='#244d37';for(const q of[[0,-67,36],[-23,-48,25],[23,-48,25]]){ctx.beginPath();ctx.arc(q[0],q[1],q[2],0,7);ctx.fill()}ctx.fillStyle='#3f7047';ctx.beginPath();ctx.arc(-9,-72,17,0,7);ctx.fill();ctx.restore()}
const frame=(im,i,count,w,h)=>{if(!im.complete||!im.naturalWidth)return false;const fw=im.naturalWidth/count;ctx.drawImage(im,Math.floor(i)%count*fw,0,fw,im.naturalHeight,w,h);return true};
function building(b){let x=b.x-worldX,y=ground();if(x<-180||x>W+180)return;const key=b.type+'.png';if(A[key]&&A[key].complete){const sz=b.type==='castle'?[150,125]:[125,105];ctx.drawImage(A[key],x-sz[0]/2,y-sz[1],sz[0],sz[1]);return}ctx.fillStyle='#777';ctx.fillRect(x-50,y-80,100,80)}
function sprite(kind,x,y,scale=1){const key=kind+'.png',im=A[key],count=kind==='king'?8:6;if(!im||!im.complete)return;const fw=im.naturalWidth/count,fh=im.naturalHeight;const bob=Math.sin(time*7+x*.01)*1.5;ctx.imageSmoothingEnabled=false;ctx.drawImage(im,Math.floor(time*8)%count*fw,0,fw,fh,x-fw*scale/2,y-fh*scale+bob,fw*scale,fh*scale)}
function shepherd(){sprite('king',W*.5,ground()-2,1.15)}function unit(u){sprite(u.kind,u.x-worldX,ground()+2,u.kind==='enemy'?1.0:.82)}
function burst(x,y,hit=false){for(let i=0;i<(hit?18:10);i++)particles.push({x,y,vx:rnd(-90,90),vy:rnd(-150,-30),life:.7,max:.7,hit})}
function build(type){const cost={farm:[30,0],house:[35,0],wall:[0,25],tower:[70,0],worker:[20,0],archer:[45,0]}[type];if(!cost||ui.gold<cost[0]||ui.wood<cost[1])return say('الموارد غير كافية');if((type==='worker'||type==='archer')&&ui.pop>=ui.cap)return say('لا توجد مساكن كافية');ui.gold-=cost[0];ui.wood-=cost[1];const x=worldX+W*.5+rnd(-180,180);if(type==='worker'||type==='archer'){ui.pop++;units.push({kind:type,x:x+100,hp:type==='archer'?4:2});say(type==='archer'?'تم تجنيد رامي.':'تم توظيف عامل.')}else{buildings.push({type,x});if(type==='house')ui.cap+=4;say('تم بناء '+({farm:'مزرعة',house:'مسكن',wall:'سور',tower:'برج'}[type]))}sync()}
function save(){localStorage.setItem('rsk_save',JSON.stringify({ui,time,worldX,horse,night,units,buildings}));say('تم حفظ المملكة.')}function load(){try{const s=JSON.parse(localStorage.getItem('rsk_save'));if(!s)return say('لا يوجد حفظ سابق.');({ui,time,worldX,horse,night,units,buildings}=s);say('تم تحميل المملكة.');sync()}catch(e){say('تعذر تحميل الحفظ.')}}
document.querySelectorAll('#buildbar button[data-build]').forEach(b=>b.onclick=()=>build(b.dataset.build));document.getElementById('left').onpointerdown=()=>worldX-=45;document.getElementById('right').onpointerdown=()=>worldX+=45;document.getElementById('horse').onclick=()=>{horse=!horse;say(horse?'امتطيت جوادك.':'ترجلت من الجواد.')};document.getElementById('save').onclick=save;document.getElementById('load').onclick=load;document.getElementById('startBtn').onclick=()=>{running=true;document.getElementById('start').style.display='none';say('بدأت المملكة. ابنِ مسكنًا ثم وظّف العمال والرامة.');sync()};
function update(dt){if(!running||gameOver)return;time+=dt;const day=Math.floor(time/48)+1;if(day!==ui.day){ui.day=day;ui.gold+=18+units.filter(u=>u.kind==='worker').length*5;ui.wood+=10+buildings.filter(b=>b.type==='farm').length*2;ui.food+=15+units.filter(u=>u.kind==='worker').length*2;ui.level=Math.min(10,1+Math.floor(ui.day/3));say('بدأ يوم جديد. دخل المملكة وصل.')}night=time%48>32;spawn+=dt;if(night&&spawn>Math.max(2.8,5-ui.level*.18)){spawn=0;const n=Math.min(2+Math.floor(ui.day/2),9);for(let i=0;i<n;i++)units.push({kind:'enemy',x:worldX+W+rnd(140,650),hp:3+Math.floor(ui.day/5),atk:0})}for(const u of units){if(u.kind==='worker'){u.x+=Math.sin(time+u.x)*dt*6}else if(u.kind==='enemy'){const target=worldX+W*.5;u.x-=dt*(18+ui.day*1.4);u.atk=(u.atk||0)+dt;if(Math.abs(u.x-target)<95&&u.atk>.8){u.atk=0;ui.hp-=4;burst(u.x-worldX,ground()-45,true);if(ui.hp<=0){ui.hp=0;gameOver=true;say('سقطت المملكة. أعد المحاولة.');}}}}
const archers=units.filter(u=>u.kind==='archer'),enemies=units.filter(u=>u.kind==='enemy');for(const a of archers)for(const e of enemies){if(Math.abs(a.x-e.x)<190&&Math.random()<dt*1.7){e.hp--;burst(e.x-worldX,ground()-65,true)}}units=units.filter(u=>u.kind!=='enemy'||u.hp>0);ui.gold+=units.filter(u=>u.kind==='worker').length*dt*.1;ui.wood+=buildings.filter(b=>b.type==='farm').length*dt*.04;ui.food=Math.max(0,ui.food-units.length*dt*.012);for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=220*dt;p.life-=dt}particles=particles.filter(p=>p.life>0);sync()}
function render(){sky();const gy=ground();ctx.fillStyle='#4f7d46';ctx.fillRect(0,gy,W,H-gy);for(let x=-(worldX%64);x<W;x+=64){ctx.fillStyle='#5f914f';ctx.fillRect(x,gy,40,3)}for(const t of trees){const x=t.x-worldX;if(x>-100&&x<W+100)tree(x,gy,t.s)}for(const b of buildings)building(b);for(const u of units)if(u.kind!=='enemy')unit(u);for(const e of units)if(e.kind==='enemy')unit(e);shepherd();for(const p of particles){ctx.globalAlpha=clamp(p.life/p.max,0,1);ctx.fillStyle=p.hit?'#ff7b61':'#f4ca63';ctx.fillRect(p.x,p.y,4,4);ctx.globalAlpha=1}if(night){ctx.fillStyle='rgba(6,10,24,.38)';ctx.fillRect(0,0,W,H);ctx.fillStyle='#f4e5b2';ctx.beginPath();ctx.arc(W-90,95,30,0,7);ctx.fill()}if(gameOver){ctx.fillStyle='rgba(4,7,12,.75)';ctx.fillRect(0,0,W,H);ctx.fillStyle='#fff';ctx.textAlign='center';ctx.font='700 34px system-ui';ctx.fillText('سقطت المملكة',W/2,H/2-20);ctx.font='18px system-ui';ctx.fillText('اضغط إعادة تحميل الصفحة لبدء حملة جديدة',W/2,H/2+25);ctx.textAlign='start'}}
let last=performance.now();function loop(now){const dt=Math.min(.05,(now-last)/1000);last=now;update(dt);render();requestAnimationFrame(loop)}sync();loop(last);