const C=document.getElementById('world'),ctx=C.getContext('2d');let W,H,DPR=1;function resize(){DPR=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;C.width=W*DPR;C.height=H*DPR;ctx.setTransform(DPR,0,0,DPR,0,0)}addEventListener('resize',resize);resize();
const ui={gold:120,wood:80,food:60,pop:4,cap:12,day:1,level:1};let running=false,time=0,worldX=0,horse=false,spawn=0,night=false,msg='ابنِ اقتصادك واستعد لليل.',units=[],buildings=[{type:'castle',x:520}],particles=[],trees=[];
const rnd=(a,b)=>a+Math.random()*(b-a),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));function say(s){msg=s;document.getElementById('message').textContent=s}for(let i=0;i<40;i++)trees.push({x:i*150+rnd(-40,40),s:rnd(.75,1.25)});
function sync(){for(const k of ['gold','wood','food','day','level'])document.getElementById(k).textContent=Math.floor(ui[k]);document.getElementById('pop').textContent=ui.pop+'/'+ui.cap;document.getElementById('phase').textContent=night?'ليل':'نهار'}
function ground(){return H*.72}
function sky(){let g=ctx.createLinearGradient(0,0,0,H);if(night){g.addColorStop(0,'#10182d');g.addColorStop(.6,'#30445e');g.addColorStop(1,'#5b4936')}else{g.addColorStop(0,'#78c8ef');g.addColorStop(.55,'#c8e8d2');g.addColorStop(1,'#d9c28a')}ctx.fillStyle=g;ctx.fillRect(0,0,W,H)}
function mountain(x,y,s,c){ctx.fillStyle=c;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+160*s,y-150*s);ctx.lineTo(x+310*s,y);ctx.closePath();ctx.fill()}
function tree(x,y,s){ctx.save();ctx.translate(x,y);ctx.scale(s,s);ctx.fillStyle='#513725';ctx.fillRect(-7,-45,14,48);ctx.fillStyle='#254f39';ctx.beginPath();ctx.arc(0,-60,35,0,7);ctx.arc(-23,-43,25,0,7);ctx.arc(23,-42,25,0,7);ctx.fill();ctx.fillStyle='#3b7046';ctx.beginPath();ctx.arc(-10,-69,17,0,7);ctx.fill();ctx.restore()}
function castle(b){let x=b.x-worldX,y=ground();ctx.save();ctx.translate(x,y);ctx.fillStyle='#776f67';ctx.fillRect(-65,-125,130,125);ctx.fillStyle='#625b56';ctx.fillRect(-92,-150,45,150);ctx.fillRect(47,-150,45,150);ctx.fillStyle='#8e857a';ctx.fillRect(-15,-78,30,78);ctx.fillStyle='#bca57a';ctx.fillRect(-5,-50,10,50);ctx.fillStyle='#e6c36b';ctx.fillRect(-25,-115,50,26);ctx.fillStyle='#1d2933';ctx.fillRect(-14,-109,28,18);ctx.restore()}
function building(b){let x=b.x-worldX,y=ground();if(x<-160||x>W+160)return;if(b.type==='castle'){castle(b);return}ctx.save();ctx.translate(x,y);if(b.type==='farm'){ctx.fillStyle='#6d4c2b';for(let i=0;i<5;i++)ctx.fillRect(-55+i*23,-8,17,8);ctx.fillStyle='#7dbb52';for(let i=0;i<5;i++){ctx.beginPath();ctx.arc(-47+i*23,-25,11,0,7);ctx.fill()}ctx.fillStyle='#d7b276';ctx.fillRect(-60,-60,120,15)}if(b.type==='house'){ctx.fillStyle='#b97b49';ctx.fillRect(-45,-65,90,65);ctx.fillStyle='#754735';ctx.beginPath();ctx.moveTo(-58,-65);ctx.lineTo(0,-112);ctx.lineTo(58,-65);ctx.fill();ctx.fillStyle='#2f2520';ctx.fillRect(-12,-38,24,38)}if(b.type==='wall'){ctx.fillStyle='#8c8b83';ctx.fillRect(-55,-75,110,75);ctx.fillStyle='#6e6d68';for(let i=-50;i<55;i+=22)ctx.fillRect(i,-84,14,9)}if(b.type==='tower'){ctx.fillStyle='#8e8b82';ctx.fillRect(-28,-130,56,130);ctx.fillStyle='#65645f';ctx.fillRect(-37,-140,74,13);ctx.fillStyle='#3a3430';ctx.fillRect(-9,-105,18,22)}ctx.restore()}
function shepherd(){let x=W*.5,y=ground()-70;ctx.save();ctx.translate(x,y);if(horse){ctx.fillStyle='#7d5137';ctx.beginPath();ctx.ellipse(0,28,45,20,0,0,7);ctx.fill();ctx.fillRect(27,4,12,30);ctx.fillStyle='#d5a35b';ctx.beginPath();ctx.arc(42,-4,15,0,7);ctx.fill();ctx.fillStyle='#c98c55';ctx.fillRect(-10,-38,22,38)}else{ctx.fillStyle='#27485d';ctx.fillRect(-12,-42,24,42);ctx.fillStyle='#d9a06a';ctx.beginPath();ctx.arc(0,-55,15,0,7);ctx.fill();ctx.fillStyle='#4d3527';ctx.fillRect(-18,-70,36,8);ctx.fillStyle='#c9d0d5';ctx.fillRect(-21,-40,42,10)}ctx.restore()}
function unit(u){let x=u.x-worldX,y=ground()-25;ctx.save();ctx.translate(x,y);if(u.kind==='archer'){ctx.fillStyle='#b9c4c9';ctx.fillRect(-7,-25,14,25);ctx.fillStyle='#d9a06a';ctx.beginPath();ctx.arc(0,-34,10,0,7);ctx.fill();ctx.strokeStyle='#b08a4f';ctx.beginPath();ctx.arc(15,-28,12,-1.4,1.4);ctx.stroke()}else{ctx.fillStyle='#5f8154';ctx.fillRect(-8,-25,16,25);ctx.fillStyle='#d9a06a';ctx.beginPath();ctx.arc(0,-34,10,0,7);ctx.fill()}ctx.restore()}
function enemy(e){let x=e.x-worldX,y=ground()-30;ctx.save();ctx.translate(x,y);ctx.fillStyle='#24202a';ctx.beginPath();ctx.ellipse(0,-15,17,27,0,0,7);ctx.fill();ctx.fillStyle='#d56d52';ctx.beginPath();ctx.arc(-5,-43,8,0,7);ctx.arc(7,-43,8,0,7);ctx.fill();ctx.fillStyle='#f1cf78';ctx.fillRect(-6,-20,4,4);ctx.restore()}
function burst(x,y){for(let i=0;i<10;i++)particles.push({x,y,vx:rnd(-80,80),vy:rnd(-120,-30),life:.7})}
function build(type){const cost={farm:[30,0],house:[35,0],wall:[0,25],tower:[70,0],worker:[20,0],archer:[45,0]}[type];if(ui.gold<cost[0]||ui.wood<cost[1])return say('الموارد غير كافية');if((type==='worker'||type==='archer')&&ui.pop>=ui.cap)return say('لا توجد مساكن كافية');ui.gold-=cost[0];ui.wood-=cost[1];let x=worldX+W*.5+rnd(-180,180);if(type==='worker'||type==='archer'){ui.pop++;units.push({kind:type==='archer'?'archer':'worker',x:x+100});say(type==='archer'?'تم تجنيد رامي.':'تم توظيف عامل.')}else{buildings.push({type,x});if(type==='house')ui.cap+=4;say('تم بناء '+({farm:'مزرعة',house:'مسكن',wall:'سور',tower:'برج'}[type]))}sync()}
document.querySelectorAll('#buildbar button').forEach(b=>b.onclick=()=>build(b.dataset.build));document.getElementById('left').onpointerdown=()=>worldX-=35;document.getElementById('right').onpointerdown=()=>worldX+=35;document.getElementById('horse').onclick=()=>{horse=!horse;say(horse?'امتطيت جوادك.':'ترجلت من الجواد.')};document.getElementById('startBtn').onclick=()=>{running=true;document.getElementById('start').style.display='none';say('ابدأ بجمع الموارد وبناء الدفاعات.');sync()};
function update(dt){if(!running)return;time+=dt;let day=Math.floor(time/48)+1;if(day!==ui.day){ui.day=day;ui.gold+=18+units.filter(u=>u.kind==='worker').length*4;ui.food+=12;ui.wood+=10;ui.level=Math.min(10,1+Math.floor(ui.day/3));say('بدأ يوم جديد. حصلت المملكة على دخلها.')}night=time%48>32;spawn+=dt;if(night&&spawn>5){spawn=0;for(let i=0;i<Math.min(2+Math.floor(ui.day/2),7);i++)units.push({kind:'enemy',x:worldX+W+rnd(80,500),hp:3})}for(const u of units){if(u.kind==='worker')u.x+=Math.sin(time+u.x)*dt*5;else if(u.kind==='enemy')u.x-=dt*(18+ui.day*1.3)}for(const e of units.filter(u=>u.kind==='enemy'))for(const a of units.filter(u=>u.kind==='archer'))if(Math.abs(a.x-e.x)<180&&Math.random()<dt*.8){e.hp--;burst(e.x-worldX,ground()-55)}units=units.filter(u=>u.kind!=='enemy'||u.hp>0);for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=180*dt;p.life-=dt}particles=particles.filter(p=>p.life>0);ui.gold+=units.filter(u=>u.kind==='worker').length*dt*.08;ui.food=Math.max(0,ui.food-units.length*dt*.012);sync()}
function render(){sky();let gy=ground();ctx.fillStyle='#4b7b43';ctx.fillRect(0,gy,W,H-gy);ctx.fillStyle='#365f38';for(let x=-(worldX%50);x<W;x+=50)ctx.fillRect(x,gy,2,10);mountain(-worldX*.12,gy,1.4,'#6d8a86');mountain(250-worldX*.08,gy,1.1,'#58736f');for(const t of trees){let x=t.x-worldX;if(x>-100&&x<W+100)tree(x,gy,t.s)}for(const b of buildings)building(b);for(const u of units)if(u.kind!=='enemy')unit(u);for(const e of units)if(e.kind==='enemy')enemy(e);shepherd();for(const p of particles){ctx.globalAlpha=clamp(p.life/.7,0,1);ctx.fillStyle='#e6c36b';ctx.fillRect(p.x,p.y,4,4);ctx.globalAlpha=1}if(night){ctx.fillStyle='rgba(8,13,29,.30)';ctx.fillRect(0,0,W,H);ctx.fillStyle='#f4e5b2';ctx.beginPath();ctx.arc(W-90,100,30,0,7);ctx.fill()}}
let last=performance.now();function loop(now){const dt=Math.min(.05,(now-last)/1000);last=now;update(dt);render();requestAnimationFrame(loop)}sync();loop(last);