import {GameState,BUILD_COSTS,EnemyState,ProjectileState} from "../core/Types";import {TimeManager} from "../core/TimeManager";
function can(s:GameState,c:any){return Object.entries(c).every(([k,v])=>(s.resources as any)[k]>=(v as number))}
function pay(s:GameState,c:any){for(const [k,v] of Object.entries(c))if(v)(s.resources as any)[k]-=v as number}
function nearest<T extends {x:number}>(a:T[],x:number){let b:T|undefined,d=1e9;for(const v of a){const q=Math.abs(v.x-x);if(q<d){d=q;b=v}}return b}
export class WorldSimulation{
 moveX=0;attack=false;coin=false;build=false;upgrade=false;private spawnTimer=0;private foodTimer=0;private trainTimer=0;private resourceTimer=0;private lastSeason=0;
 constructor(public state:GameState,public time:TimeManager){}
 update(dt:number){
  const s=this.state,t=this.time;t.update(dt);s.time=t.elapsed;s.day=t.day;s.seasonIndex=t.seasonIndex;s.weather=t.weather;
  this.player(dt);this.units(dt);this.crops(dt);this.animals(dt);this.economy(dt);this.resourceTimer+=dt;if(this.resourceTimer>10){this.resourceTimer=0;this.gatherResources();}this.night(dt);this.defenses(dt);this.projectiles(dt);
  if(this.attack){this.attack=false;this.melee()}if(this.coin)this.recruit();if(this.build)this.place();if(this.upgrade){this.upgrade=false;this.castleUpgrade()}
  this.cleanup()
 }
 player(dt:number){const s=this.state,spd=s.player.stamina<10?72:135,mod=tweak(this.time);s.player.x=Math.max(-2300,Math.min(2300,s.player.x+this.moveX*spd*mod*dt));if(this.moveX)s.player.facing=this.moveX>0?1:-1;s.player.stamina=Math.max(0,Math.min(100,s.player.stamina+(Math.abs(this.moveX)<.1?20:-14)*dt));s.player.attackTimer=Math.max(0,s.player.attackTimer-dt)}
 units(dt:number){const s=this.state;this.trainTimer+=dt;for(const u of s.units){const e=nearest(s.enemies,u.x);if((u.role==="guard"||u.role==="archer")&&e&&Math.abs(e.x-u.x)<320){u.state="fight";if(u.role==="archer"&&Math.random()<dt*.9)this.arrow(u.x,54,e.x);else if(Math.abs(e.x-u.x)<70)e.hp-=dt*18}else if(u.role==="farmer"){const c=nearest(s.crops,u.x);u.state="work";if(c&&c.stage<3){u.x+=Math.sign(c.x-u.x)*18*dt;c.water=Math.min(100,c.water+dt*6)}else u.x+=Math.sin(s.time*.4+u.homeX)*dt*3}else{u.state="patrol";u.x+=Math.sin(s.time*.4+u.homeX)*dt*7}}
  if(this.trainTimer>28){this.trainTimer=0;const yard=s.buildings.some(b=>b.kind==="training"),v=s.units.find(u=>u.role==="villager");if(yard&&v&&s.resources.iron>=3){s.resources.iron-=3;v.role="guard";v.rank=1;v.state="patrol"}}
 }
 crops(dt:number){const s=this.state;for(const c of s.crops){let r=this.time.season==="spring"?1.15:this.time.season==="autumn"?.8:1;if(this.time.season==="winter"&&c.kind!=="winter")r=0;if(this.time.weather==="rain")r*=1.15;c.age+=dt*r;if(c.stage<3&&c.age>35+c.stage*25)c.stage=(c.stage+1) as any;if(c.stage===3&&Math.random()<dt*.02)s.resources.food++}}
 animals(dt:number){const s=this.state;for(const a of s.animals){a.age+=dt;const wild=a.wild;if(wild&&this.time.phase==="night")a.x+=Math.sin(a.age)*dt*22;else a.x+=Math.sin(s.time*.2+a.age)*dt*(wild?5:2);if(!wild&&a.kind!=="horse"&&Math.random()<dt*.006)s.resources.milk++}if(this.lastSeason!==s.seasonIndex){this.lastSeason=s.seasonIndex;const parents=s.animals.filter(a=>!a.wild&&a.kind!=="horse").slice(0,8);for(const p of parents)if(Math.random()<.35)s.animals.push({id:"a"+Date.now()+Math.random(),kind:p.kind,x:p.x+20,age:0,state:"graze",wild:false})}}
 economy(dt:number){this.foodTimer+=dt;if(this.foodTimer>20){this.foodTimer=0;this.state.resources.food=Math.max(0,this.state.resources.food-this.state.units.length)}}\n gatherResources(){const s=this.state;const builders=s.units.filter(u=>u.role==="builder").length;const farms=s.units.filter(u=>u.role==="farmer").length;s.resources.wood=Math.min(999,s.resources.wood+builders*2);s.resources.stone=Math.min(999,s.resources.stone+Math.max(1,Math.floor(builders/2)));s.resources.food=Math.min(999,s.resources.food+farms);if(s.resources.milk>20){s.resources.milk-=20;s.resources.food+=3}}
 night(dt:number){const s=this.state;if(this.time.phase!=="night"){this.spawnTimer=0;return}this.spawnTimer+=dt;if(this.spawnTimer>=10){this.spawnTimer=0;const side=Math.random()<.5?-1:1;const hard=1+(s.day-1)*.16+(this.time.season==="winter"?.25:0);const brute=Math.random()<Math.min(.35,.08+s.day*.012);const hp=Math.round((brute?110:50)*hard);s.enemies.push({id:"e"+Date.now()+Math.random(),x:s.player.x+side*(560+Math.random()*180),hp,maxHp:hp,speed:(brute?18:31)*hard,damage:brute?10:4,kind:brute?"brute":Math.random()<.25?"scout":"greedling"});s.wave=Math.floor(s.day/2)+1}}
 defenses(dt:number){const s=this.state;if(this.time.phase!=="night")return;for(const b of s.buildings){const e=nearest(s.enemies,b.x);if(!e||Math.abs(e.x-b.x)>360)continue;if(b.kind==="tower"&&Math.random()<dt*.6)this.arrow(b.x,130,e.x);if(b.kind==="cannon"&&s.resources.oil>0&&s.resources.iron>0&&Math.random()<dt*.25){s.resources.oil--;s.resources.iron--;s.projectiles.push({id:"pc"+Date.now()+Math.random(),x:b.x,y:95,vx:Math.sign(e.x-b.x)*260,vy:-240,damage:85,kind:"cannon",life:3})}}}
 projectiles(dt:number){const s=this.state;for(let i=s.projectiles.length-1;i>=0;i--){const p=s.projectiles[i];p.life-=dt;p.vy+=420*dt;p.x+=p.vx*dt;p.y+=p.vy*dt;let hit=false;for(const e of s.enemies)if(Math.abs(e.x-p.x)<30&&Math.abs(30-p.y)<38){e.hp-=p.damage;hit=true;break}if(p.life<=0||p.y>160||hit)s.projectiles.splice(i,1)}for(const e of s.enemies){e.x+=Math.sign(s.player.x-e.x)*e.speed*dt;for(const b of s.buildings)if((b.kind==="wall"||b.kind==="gate"||b.kind==="tower")&&Math.abs(b.x-e.x)<34){b.hp-=e.damage*dt;e.x-=Math.sign(s.player.x-e.x)*e.speed*dt}}}
 melee(){const s=this.state;if(s.player.attackTimer>0)return;s.player.attackTimer=.5;const range=s.player.weapon==="spear"?112:s.player.weapon==="axe"?92:80,dmg=s.player.weapon==="axe"?38:s.player.weapon==="spear"?28:22;for(const e of s.enemies)if(Math.abs(e.x-s.player.x)<range)e.hp-=dmg}
 recruit(){this.coin=false;const s=this.state;if(s.resources.coins<1)return;const v=s.units.find(u=>u.role==="villager"&&Math.abs(u.x-s.player.x)<280);if(v){s.resources.coins--;v.role="farmer";v.state="work";return}s.resources.coins--;s.units.push({id:"u"+Date.now()+Math.random(),role:"villager",rank:1,x:s.player.x+s.player.facing*70,hp:70,maxHp:70,state:"idle",homeX:s.player.x+s.player.facing*70})}
 place(){this.build=false;const s=this.state,c=BUILD_COSTS[s.selectedBuild];if(!can(s,c))return;pay(s,c);const hp:any={wall:180,tower:260,farm:160,barn:240,blacksmith:260,training:250,house:180,cannon:220};const x=Math.round((s.player.x+s.player.facing*120)/10)*10;s.buildings.push({id:"b"+Date.now()+Math.random(),kind:s.selectedBuild,x,level:1,hp:hp[s.selectedBuild],maxHp:hp[s.selectedBuild]})}
 castleUpgrade(){const s=this.state,castle=s.buildings.find(b=>b.kind==="castle");if(!castle||Math.abs(castle.x-s.player.x)>190||s.castleLevel>=3)return;const costs=s.castleLevel===1?{wood:120,stone:90,iron:20}:{wood:220,stone:160,iron:45};if(!can(s,costs))return;pay(s,costs);s.castleLevel++;castle.level=s.castleLevel;castle.maxHp+=450;castle.hp=castle.maxHp;if(s.castleLevel===2){s.buildings.push({id:"royalTower",kind:"tower",x:180,level:1,hp:260,maxHp:260})}else{s.buildings.push({id:"royalCannon",kind:"cannon",x:-180,level:1,hp:220,maxHp:220})}}
 cleanup(){const s=this.state;for(let i=s.enemies.length-1;i>=0;i--)if(s.enemies[i].hp<=0){s.resources.coins+=2;s.resources.meat++;s.enemies.splice(i,1)}for(let i=s.buildings.length-1;i>=0;i--)if(s.buildings[i].hp<=0&&s.buildings[i].id!=="keep")s.buildings.splice(i,1)}
 arrow(x:number,y:number,target:number){const dx=target-x;safely(this.state.projectiles.push({id:"p"+Date.now()+Math.random(),x,y,vx:Math.sign(dx)*Math.min(430,210+Math.abs(dx)*.3),vy:-180,damage:18,kind:"arrow",life:2.4}))}
}
function safely(v:any){return v}function tweak(t:TimeManager){return t.season==="winter"?.9:t.weather==="heat"?.92:1}
